apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecosaude-forecast-sa
  namespace: ecosaude
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecosaude-read-config
  namespace: ecosaude
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
