apiVersion: v1
kind: Secret
metadata:
  name: ecosaude-secrets
  namespace: ecosaude
type: Opaque
stringData:
  SATELLITE_API_KEY: "preencher-no-ambiente"
  CLIMATE_API_KEY: "preencher-no-ambiente"
  DATABASE_URL: "preencher-no-ambiente"
