apiVersion: v1
kind: Service
metadata:
  name: ecosaude-forecast-service
  namespace: ecosaude
spec:
  selector:
    app: ecosaude-forecast-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
